# Generated by Django 5.0.1 on 2025-08-08 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insights', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markettrend',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
    ]
